server:
  port: 8081
# mysql 数据库配置
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: video
      password: video@123
      url: jdbc:mysql://103.45.109.87:3306/video?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall
      filter:
        stat:
          merge-sql: true
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        #内置监控页面的首页是/druid/index.html
        url-pattern: /druid/*
        login-username: admin
        login-password: admin@123
        allow: 192.168.40.76
        enabled: true
# redis 配置
  redis:
    database: 0
    host: 103.45.109.87
    port: 6379
    password: video@123
    jedis:
      pool:
        max-active: 8
        min-idle: 2
        max-idle: 8
