server:
  servlet:
    context-path: /video
spring:
  profiles:
    active: dev

security:
  ignore:
    uris:
      - /v2/**
      - /webjars/**
      - /swagger-resources/**
      - /error
      - /*.html
