server:
  servlet:
    context-path: /video
spring:
  application:
    name: video
  profiles:
    active: dev
  quartz:
    properties:
      org:
        schedule:
          instanceName: quartzSchedule
          instanceId: auto
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 10
      threadPriority: 5
      threadsInheritContextClassLoaderOfInitializingThread: true
security:
  ignore:
    uris:
      - /v2/**
      - /webjars/**
      - /swagger-resources/**
      - /error
      - /*.html
      - /druid/**
      - /templates/**
      - /test/**


