version: "3.7.5"
services:
  nginx:
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    image: nginx:latest
    restart: always
    container_name: nginx
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: video
      MYSQL_USER: video
      MYSQL_PASSWORD: video@123
    container_name: mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    container_name: redis
  video:
    image: video-test:latest
    restart: always
    ports:
      - 8080:8081
    volumes:
      - /opt/video:/opt/video
    depends_on:
      - mysql
      - redis
      - nginx
    container_name: video-test